server:
  port: 9000
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

spring:
  cloud:
    gateway:
      #Enables the gateway to create routes based on services registered with service discovery
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
