server:
  port: 9000
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


spring:
  cloud:
    gateway:
      #Enables the gateway to create routes based on services registered with service discovery
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

      #Manual routes
      routes:
        #This optional ID is an arbitrary route ID
        - id: organization-service
        #Sets the route’s destination URI
        uri: lb://organization-service
        #The path, although set by the load() method, is just another option.
        predicates:
          - Path=/organization/**
        #Filters a collection of Spring web.filters to modify the request or response before or after sending the response
        filters:
          #Rewrites the request path, from /organization/** to /**, by taking the path regexp as a parameter and a replacement order
          - RewritePath=/organization/(?<path>.*), /$\{path}


management:
  endpoints:
    web.exposure.include: "*"
    enabled-by-default: true

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com: DEBUG
