spring:
  jpa:
    generate-ddl : true
    hibernate:
      ddl-auto: update
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    show-sql : true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    testWhileIdle : true
    validationQuery : SELECT 1
    url : jdbc:postgresql://localhost:5432/ostock_dev?sslmode:disable

    username : postgres
    password : "{cipher}a825ffbcc49876d271230e0838fa2a70afe07a6603503a754c68f8fb32e583e2"

eureka:
  instance:
    preferIpAddress : true
  client:
    registerWithEureka : true
    fetchRegistry : true
    serviceUrl:
      defaultZone : http://localhost:8761/eureka

server:
  port : 8081

management:
  endpoints:
    web.exposure.include: "*"
    enabled-by-default: true
